spring:
  servlet:
    #配置上传文件
    multipart:
      max-file-size: 10MB       #上传文件大小限制
      max-request-size: 100MB
  #配置数据源
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/neweast?serverTimezone=UTC
      username: root
      password: '0825'
      aop-patterns: com.zong.east.*  #springbean监控
      filters: stat,wall,slf4j  #所有开启的功能
      stat-view-servlet:   #监控页配置
        enabled: true
        login-username: admin
        login-password: admin
        reset-enable: false
      web-stat-filter:  #web监控
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'

      filter: #sql监控
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true

#配置mybatis
mybatis:
  configuration:  #指定mybatis全局配置文件中的相关配置项
    map-underscore-to-camel-case: true